#!/usr/bin/env python3
"""Generate _redirects: one 301 per page, extensionless form -> canonical .html.

Netlify serves every page at BOTH /foo and /foo.html with a 200. Search Console
showed Google indexing the extensionless form and earning impressions on it,
while the page's own canonical points at .html -- so the ranking URL was one the
site disowns. These rules collapse that back to one URL per page.

Rules are explicit and forced (301!). Explicit because a /* wildcard would also
catch /, /ar/ and asset paths; forced because it must win regardless of how
Netlify orders redirects against its pretty-URL mapping.
"""
import pathlib, sys

repo = pathlib.Path(sys.argv[1])
rows = []
for f in sorted(repo.rglob("*.html")):
    if ".git" in f.parts:
        continue
    rel = f.relative_to(repo).as_posix()
    if rel == "404.html" or rel.endswith("index.html"):
        continue                      # dir roots are canonical as /path/; 404 stays unlinked
    rows.append((f"/{rel[:-5]}", f"/{rel}"))

w = max(len(a) for a, _ in rows)
out = [
    "# Generated by build_redirects.py -- do not hand-edit.",
    "# One 301 per page: the extensionless URL Netlify also serves collapses",
    "# onto the .html URL every canonical already declares.",
    "",
]
out += [f"{a.ljust(w)}  {b}  301!" for a, b in rows]
(repo / "_redirects").write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"  {len(rows)} redirect rules -> {repo/'_redirects'}")
